domain=ussenterprise
domain-needed
no-resolv
bogus-priv
strict-order
no-hosts
#expand-hosts
local=/ussenterprise/
#localise-queries
server=2a07:a8c1::
server=45.90.30.0
server=2a07:a8c0::
server=45.90.28.0
add-cpe-id=ae661a
